<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\SoftwareIcon.ico</ApplicationIcon>
    <AssemblyName>AvatarExplorer</AssemblyName>
  </PropertyGroup>
	
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
    <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
    <PackageReference Include="PDFtoImage" Version="5.2.1" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
    <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
    <PackageReference Include="Message.Avalonia" Version="2.0.0" />
		<ProjectReference Include="..\AvatarExplorer.Core/AvatarExplorer.Core.csproj" />

    <Content Include="..\AvatarExplorer.Core\Data\Localization\**\*.json">
      <Link>locales\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>

    <AvaloniaResource Include="Assets\Internal\**" />
    <AvaloniaResource Include="Assets\Fonts\**\*.ttf" />
    <AvaloniaResource Include="Assets\Fonts\**\*.otf" />

  </ItemGroup>
</Project>
