<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ErrorOr" Version="2.1.1" />
		<PackageReference Include="SemanticVersioning" Version="3.0.0" />
		<PackageReference Include="SharpCompress" Version="0.49.1" />

		<Content Include="../THIRD_PARTY_LICENSES.txt">
			<Link>THIRD_PARTY_LICENSES.txt</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>

		<Content Include="../LICENSE.txt">
			<Link>LICENSE.txt</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<Target Name="GenerateLocalizationKeys" BeforeTargets="BeforeBuild">
		<Exec Command="dotnet run --project ../Tools/LocalizationKeyGenerator/LocalizationKeyGenerator.csproj" />
	</Target>
</Project>
