using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AvatarExplorer.SourceGenerator;

[Generator]
public sealed class LocalizationKeySourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonProvider = context.AdditionalTextsProvider
            .Where(static file => System.IO.Path.GetFileName(file.Path)
                .Equals("ja-JP.json", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(jsonProvider, static (ctx, file) =>
        {
            var text = file.GetText(ctx.CancellationToken);
            if (text is null)
                return;

            var source = GenerateSource(text.ToString());
            ctx.AddSource("LocalizationKey.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateSource(string json)
    {
        var keys = ParseJsonKeys(json);
        var tree = BuildTree(keys);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace AvatarExplorer.Core.Localization;");
        sb.AppendLine();
        sb.AppendLine("public static class LocalizationKey");
        sb.AppendLine("{");
        WriteClass(tree, sb, 1);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static IEnumerable<string> ParseJsonKeys(string json)
    {
        // Match JSON string keys (text between quotes followed by a colon)
        var pattern = new Regex(@"""([^""]+)""\s*:");
        foreach (Match match in pattern.Matches(json))
        {
            yield return match.Groups[1].Value;
        }
    }

    private static Dictionary<string, object> BuildTree(IEnumerable<string> keys)
    {
        var tree = new Dictionary<string, object>();
        foreach (var key in keys)
        {
            var parts = key.Split('.');
            var current = tree;

            for (var i = 0; i < parts.Length; i++)
            {
                var part = Sanitize(parts[i]);

                if (i == parts.Length - 1)
                {
                    current[part] = key;
                }
                else
                {
                    if (!current.TryGetValue(part, out var childObj) || !(childObj is Dictionary<string, object>))
                    {
                        childObj = new Dictionary<string, object>();
                        current[part] = childObj;
                    }

                    current = (Dictionary<string, object>)childObj;
                }
            }
        }

        return tree;
    }

    private static void WriteClass(Dictionary<string, object> dict, StringBuilder sb, int indent)
    {
        var indentStr = new string(' ', indent * 4);
        foreach (var kvp in dict)
        {
            if (kvp.Value is string fullKey)
            {
                sb.AppendLine($"{indentStr}public const string {kvp.Key} = \"{fullKey}\";");
            }
            else if (kvp.Value is Dictionary<string, object> child)
            {
                sb.AppendLine($"{indentStr}public static class {kvp.Key}");
                sb.AppendLine($"{indentStr}{{");
                WriteClass(child, sb, indent + 1);
                sb.AppendLine($"{indentStr}}}");
            }
        }
    }

    private static string Sanitize(string input)
    {
        if (input.Length == 0)
            return "_";

        var sb = new StringBuilder();
        if (!char.IsLetter(input[0]))
            sb.Append('_');

        foreach (var c in input)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');

        return sb.ToString();
    }
}
