/// ****************************************************************************************************
///
/// <auto-generated>
///     This file was generated during the build process from shared locale data (Data/Localization/ja-JP.json).
///     DO NOT EDIT THIS FILE MANUALLY.
///
///     To regenerate, run `dotnet run` in the LocalizationKeyGenerator project
///     or build the AvatarExplorer.Core project.
/// </auto-generated>
///
/// ****************************************************************************************************

namespace AvatarExplorer.Core.Localization;

public static class Loc
{
    public const string LanguageName = "LanguageName";
    public const string LanguagePriority = "LanguagePriority";
    public const string BoothLanguageCode = "BoothLanguageCode";
    public const string FontFamily = "FontFamily";
    public static class Title
    {
        public const string AdministratorMode = "Title.AdministratorMode";
    }
    public static class Main
    {
        public static class Search
        {
            public const string Placeholder = "Main.Search.Placeholder";
        }
        public const string AddItem = "Main.AddItem";
        public static class Filter
        {
            public const string Avatar = "Main.Filter.Avatar";
            public const string Author = "Main.Filter.Author";
            public const string Category = "Main.Filter.Category";
        }
        public static class Path
        {
            public const string Placeholder = "Main.Path.Placeholder";
            public const string SearchResult = "Main.Path.SearchResult";
        }
    }
    public static class ItemCategory
    {
        public const string Avatar = "ItemCategory.Avatar";
        public const string Clothing = "ItemCategory.Clothing";
        public const string Texture = "ItemCategory.Texture";
        public const string Gimmick = "ItemCategory.Gimmick";
        public const string Accessory = "ItemCategory.Accessory";
        public const string HairStyle = "ItemCategory.HairStyle";
        public const string Animation = "ItemCategory.Animation";
        public const string Tool = "ItemCategory.Tool";
        public const string Shader = "ItemCategory.Shader";
        public const string All = "ItemCategory.All";
    }
    public static class Button
    {
        public static class Description
        {
            public static class Item
            {
                public const string Author = "Button.Description.Item.Author";
                public const string Count = "Button.Description.Item.Count";
            }
            public static class File
            {
                public const string Extension = "Button.Description.File.Extension";
                public const string NoExtension = "Button.Description.File.NoExtension";
            }
            public static class CommonAvatar
            {
                public const string Count = "Button.Description.CommonAvatar.Count";
            }
            public static class BulkImportPreset
            {
                public const string Count = "Button.Description.BulkImportPreset.Count";
            }
            public const string TempAvatar = "Button.Description.TempAvatar";
        }
        public static class Tag
        {
            public const string CommonAvatar = "Button.Tag.CommonAvatar";
        }
        public static class ToolTip
        {
            public const string CreatedDate = "Button.ToolTip.CreatedDate";
            public const string UpdatedDate = "Button.ToolTip.UpdatedDate";
            public const string FilePath = "Button.ToolTip.FilePath";
        }
        public const string SelectVisible = "Button.SelectVisible";
        public const string Close = "Button.Close";
        public const string Confirm = "Button.Confirm";
        public const string Cancel = "Button.Cancel";
    }
    public static class ItemWindow
    {
        public const string CurrentPage = "ItemWindow.CurrentPage";
        public const string PageItemCount = "ItemWindow.PageItemCount";
    }
    public static class Dialog
    {
        public static class Confirmation
        {
            public const string Default = "Dialog.Confirmation.Default";
            public const string RemoveItem = "Dialog.Confirmation.RemoveItem";
            public const string ResetDatabase = "Dialog.Confirmation.ResetDatabase";
            public const string RemoveCommonAvatarGroup = "Dialog.Confirmation.RemoveCommonAvatarGroup";
            public const string RemoveTempAvatar = "Dialog.Confirmation.RemoveTempAvatar";
            public const string RemovePreset = "Dialog.Confirmation.RemovePreset";
            public const string AddToExistingItem = "Dialog.Confirmation.AddToExistingItem";
            public const string ResolveTempAvatar = "Dialog.Confirmation.ResolveTempAvatar";
            public const string RemoveAssetData = "Dialog.Confirmation.RemoveAssetData";
            public const string CopyAssetData = "Dialog.Confirmation.CopyAssetData";
            public const string NoAvatarsAndValidateType = "Dialog.Confirmation.NoAvatarsAndValidateType";
            public const string RemoveFolderFromDatabase = "Dialog.Confirmation.RemoveFolderFromDatabase";
            public const string RemoveFolder = "Dialog.Confirmation.RemoveFolder";
            public const string RemoveFolderFromApplicationManagedFolder = "Dialog.Confirmation.RemoveFolderFromApplicationManagedFolder";
            public static class EditCommonAvatars
            {
                public const string ReplaceAvatarsToGroup = "Dialog.Confirmation.EditCommonAvatars.ReplaceAvatarsToGroup";
                public const string ReplaceGroupToAvatars = "Dialog.Confirmation.EditCommonAvatars.ReplaceGroupToAvatars";
            }
            public const string DuplicateCustomCategoryName = "Dialog.Confirmation.DuplicateCustomCategoryName";
            public const string MergeCategory = "Dialog.Confirmation.MergeCategory";
        }
        public static class Title
        {
            public const string NewItemTitle = "Dialog.Title.NewItemTitle";
            public const string AddCustomCategory = "Dialog.Title.AddCustomCategory";
            public const string AddCommonAvatarGroup = "Dialog.Title.AddCommonAvatarGroup";
            public const string NewCommonAvatarGroupName = "Dialog.Title.NewCommonAvatarGroupName";
            public const string NewBulkImportPresetName = "Dialog.Title.NewBulkImportPresetName";
            public const string NewTempAvatarName = "Dialog.Title.NewTempAvatarName";
            public const string NewCustomCategoryName = "Dialog.Title.NewCustomCategoryName";
            public const string AddUrl = "Dialog.Title.AddUrl";
        }
        public const string SelectSaveFolderPath = "Dialog.SelectSaveFolderPath";
        public const string SelectFolderPath = "Dialog.SelectFolderPath";
        public const string SelectFilePath = "Dialog.SelectFilePath";
    }
    public static class Scheme
    {
        public const string Register = "Scheme.Register";
        public const string RestartAsAdmin = "Scheme.RestartAsAdmin";
        public const string RegisterSuccess = "Scheme.RegisterSuccess";
        public const string RegisterSkipped = "Scheme.RegisterSkipped";
    }
    public static class FileCategory
    {
        public const string Modification = "FileCategory.Modification";
        public const string Texture = "FileCategory.Texture";
        public const string Document = "FileCategory.Document";
        public const string Unitypackage = "FileCategory.Unitypackage";
        public const string Material = "FileCategory.Material";
        public const string UrlShortcut = "FileCategory.UrlShortcut";
        public const string Font = "FileCategory.Font";
        public const string Unknown = "FileCategory.Unknown";
    }
    public static class Processing
    {
        public const string Default = "Processing.Default";
        public const string AddContent = "Processing.AddContent";
        public static class Unitypackage
        {
            public static class Status
            {
                public const string Preparing = "Processing.Unitypackage.Status.Preparing";
                public const string Extracting = "Processing.Unitypackage.Status.Extracting";
                public const string Creating = "Processing.Unitypackage.Status.Creating";
                public const string Completed = "Processing.Unitypackage.Status.Completed";
            }
        }
        public static class Booth
        {
            public static class Status
            {
                public const string Fetching = "Processing.Booth.Status.Fetching";
            }
        }
        public static class DirectoryCopy
        {
            public const string Copying = "Processing.DirectoryCopy.Copying";
        }
        public static class Import
        {
            public const string Copying = "Processing.Import.Copying";
        }
        public static class ItemAdd
        {
            public const string Copying = "Processing.ItemAdd.Copying";
        }
    }
    public static class ContextMenu
    {
        public static class Item
        {
            public const string CheckForUpdate = "ContextMenu.Item.CheckForUpdate";
            public const string ShowOtherItemsByAuthor = "ContextMenu.Item.ShowOtherItemsByAuthor";
            public static class Add
            {
                public const string BulkImportList = "ContextMenu.Item.Add.BulkImportList";
                public const string File = "ContextMenu.Item.Add.File";
                public const string Folder = "ContextMenu.Item.Add.Folder";
            }
            public static class Booth
            {
                public const string Open = "ContextMenu.Item.Booth.Open";
                public const string Copy = "ContextMenu.Item.Booth.Copy";
            }
            public const string CopyItemInfo = "ContextMenu.Item.CopyItemInfo";
            public static class Edit
            {
                public const string Default = "ContextMenu.Item.Edit.Default";
                public const string Title = "ContextMenu.Item.Edit.Title";
                public const string Tag = "ContextMenu.Item.Edit.Tag";
                public const string Memo = "ContextMenu.Item.Edit.Memo";
                public const string DefaultPath = "ContextMenu.Item.Edit.DefaultPath";
                public const string Implemented = "ContextMenu.Item.Edit.Implemented";
            }
            public static class Thumbnail
            {
                public const string Change = "ContextMenu.Item.Thumbnail.Change";
                public const string Fetch = "ContextMenu.Item.Thumbnail.Fetch";
            }
            public const string Remove = "ContextMenu.Item.Remove";
        }
        public static class ItemFolder
        {
            public const string OpenFolder = "ContextMenu.ItemFolder.OpenFolder";
            public const string ShowInExplorer = "ContextMenu.ItemFolder.ShowInExplorer";
            public const string RemoveFolder = "ContextMenu.ItemFolder.RemoveFolder";
        }
        public static class ItemFile
        {
            public const string OpenFile = "ContextMenu.ItemFile.OpenFile";
            public const string BulkImportList = "ContextMenu.ItemFile.BulkImportList";
            public const string ShowInExplorer = "ContextMenu.ItemFile.ShowInExplorer";
            public const string OpenUnitypackageViewer = "ContextMenu.ItemFile.OpenUnitypackageViewer";
            public const string OpenPdfViewer = "ContextMenu.ItemFile.OpenPdfViewer";
        }
        public static class BulkImportPreset
        {
            public const string RemovePreset = "ContextMenu.BulkImportPreset.RemovePreset";
        }
        public static class TempAvatar
        {
            public const string EditTempAvatarName = "ContextMenu.TempAvatar.EditTempAvatarName";
            public const string ResolveTempAvatar = "ContextMenu.TempAvatar.ResolveTempAvatar";
            public const string RemoveTempAvatar = "ContextMenu.TempAvatar.RemoveTempAvatar";
        }
        public static class ItemCategory
        {
            public const string EditCustomCategoryName = "ContextMenu.ItemCategory.EditCustomCategoryName";
            public const string MergeWithOtherCategory = "ContextMenu.ItemCategory.MergeWithOtherCategory";
        }
    }
    public static class SearchFilter
    {
        public const string Default = "SearchFilter.Default";
        public const string Title = "SearchFilter.Title";
        public const string Author = "SearchFilter.Author";
        public const string Booth = "SearchFilter.Booth";
        public const string SupportedAvatar = "SearchFilter.SupportedAvatar";
        public const string Category = "SearchFilter.Category";
        public const string ItemMemo = "SearchFilter.ItemMemo";
        public const string ImplementedAvatar = "SearchFilter.ImplementedAvatar";
        public const string NotImplementedAvatar = "SearchFilter.NotImplementedAvatar";
        public const string Tag = "SearchFilter.Tag";
        public const string CommonAvatar = "SearchFilter.CommonAvatar";
        public const string SearchWord = "SearchFilter.SearchWord";
        public const string IsOrSearch = "SearchFilter.IsOrSearch";
        public const string NegationPrefix = "SearchFilter.NegationPrefix";
    }
    public static class Success
    {
        public const string Default = "Success.Default";
        public const string Import = "Success.Import";
        public const string Export = "Success.Export";
        public const string ItemAdd = "Success.ItemAdd";
        public const string ContentAdd = "Success.ContentAdd";
        public const string ItemEdit = "Success.ItemEdit";
        public const string ItemThumbnailEdit = "Success.ItemThumbnailEdit";
        public const string Remove = "Success.Remove";
        public const string RenameCustomCategory = "Success.RenameCustomCategory";
        public const string ClipboardSet = "Success.ClipboardSet";
        public const string FetchItemThumbnail = "Success.FetchItemThumbnail";
        public const string ItemFileAdd = "Success.ItemFileAdd";
        public const string ItemFolderAdd = "Success.ItemFolderAdd";
        public const string FetchAllItemThumbnails = "Success.FetchAllItemThumbnails";
        public const string RemoveFolder = "Success.RemoveFolder";
        public const string FetchAllVariationHashs = "Success.FetchAllVariationHashs";
    }
    public static class VariationUpdate
    {
        public const string UpdateAvailable = "VariationUpdate.UpdateAvailable";
        public const string NoUpdatesAvailable = "VariationUpdate.NoUpdatesAvailable";
        public const string Added = "VariationUpdate.Added";
        public const string Removed = "VariationUpdate.Removed";
        public const string Changed = "VariationUpdate.Changed";
    }
    public static class Warning
    {
        public const string Default = "Warning.Default";
        public const string RunningInAdministratorMode = "Warning.RunningInAdministratorMode";
        public const string FetchAllItemThumbnailsCancelled = "Warning.FetchAllItemThumbnailsCancelled";
        public const string FetchAllVariationHashsCancelled = "Warning.FetchAllVariationHashsCancelled";
    }
    public static class Error
    {
        public const string Default = "Error.Default";
        public const string Nothing = "Error.Nothing";
        public const string ItemNotFound = "Error.ItemNotFound";
        public const string CommonAvatarNotFound = "Error.CommonAvatarNotFound";
        public const string PresetNotFound = "Error.PresetNotFound";
        public static class Validation
        {
            public const string EmptyTitle = "Error.Validation.EmptyTitle";
            public const string EmptyAuthor = "Error.Validation.EmptyAuthor";
            public const string NotClothingWithCommonAvatar = "Error.Validation.NotClothingWithCommonAvatar";
        }
        public const string ImportFailed = "Error.ImportFailed";
        public const string ExportFailed = "Error.ExportFailed";
        public const string ItemEditFailed = "Error.ItemEditFailed";
        public const string ItemThumbnailEditFailed = "Error.ItemThumbnailEditFailed";
        public const string BulkImportFailed = "Error.BulkImportFailed";
        public const string OpenFileFailed = "Error.OpenFileFailed";
        public const string OpenFolderFailed = "Error.OpenFolderFailed";
        public const string ClipboardSetFailed = "Error.ClipboardSetFailed";
        public const string OpenUriFailed = "Error.OpenUriFailed";
        public const string FailedToGetCurrentItem = "Error.FailedToGetCurrentItem";
        public const string ImportUnitypackageFailed = "Error.ImportUnitypackageFailed";
        public const string RetrieveBoothItemFailed = "Error.RetrieveBoothItemFailed";
        public const string FetchItemThumbnailFailed = "Error.FetchItemThumbnailFailed";
        public const string FoundProcessingFailedPath = "Error.FoundProcessingFailedPath";
        public const string AddItemFileFailed = "Error.AddItemFileFailed";
        public const string AddContentFailed = "Error.AddContentFailed";
        public const string AddItemFolderFailed = "Error.AddItemFolderFailed";
        public const string TempAvatarNotFound = "Error.TempAvatarNotFound";
        public const string LicenseFileNotFound = "Error.LicenseFileNotFound";
        public const string ThirdPartyLicenseFileNotFound = "Error.ThirdPartyLicenseFileNotFound";
        public const string UnsupportedPlatform = "Error.UnsupportedPlatform";
        public const string InvalidCategory = "Error.InvalidCategory";
        public const string FetchAllItemThumbnailsFailed = "Error.FetchAllItemThumbnailsFailed";
        public const string FetchAllVariationHashsFailed = "Error.FetchAllVariationHashsFailed";
        public const string UnitypackageNotFound = "Error.UnitypackageNotFound";
        public const string InvalidUrl = "Error.InvalidUrl";
        public const string ItemPathNotFound = "Error.ItemPathNotFound";
    }
    public static class Settings
    {
        public const string Basic = "Settings.Basic";
        public static class Language
        {
            public const string Title = "Settings.Language.Title";
            public const string Description = "Settings.Language.Description";
        }
        public static class SortOrder
        {
            public const string Title = "Settings.SortOrder.Title";
            public const string Description = "Settings.SortOrder.Description";
            public static class Options
            {
                public const string Title = "Settings.SortOrder.Options.Title";
                public const string Author = "Settings.SortOrder.Options.Author";
                public const string Created = "Settings.SortOrder.Options.Created";
                public const string Updated = "Settings.SortOrder.Options.Updated";
            }
        }
        public static class SortDirection
        {
            public const string Title = "Settings.SortDirection.Title";
            public const string Description = "Settings.SortDirection.Description";
            public static class Options
            {
                public const string Ascending = "Settings.SortDirection.Options.Ascending";
                public const string Descending = "Settings.SortDirection.Options.Descending";
            }
        }
        public static class ImplementedSort
        {
            public const string Title = "Settings.ImplementedSort.Title";
            public const string Description = "Settings.ImplementedSort.Description";
            public static class Options
            {
                public const string None = "Settings.ImplementedSort.Options.None";
                public const string Implemented = "Settings.ImplementedSort.Options.Implemented";
                public const string NotImplemented = "Settings.ImplementedSort.Options.NotImplemented";
            }
        }
        public static class Theme
        {
            public const string Title = "Settings.Theme.Title";
            public const string Description = "Settings.Theme.Description";
            public static class Options
            {
                public const string Dark = "Settings.Theme.Options.Dark";
                public const string Light = "Settings.Theme.Options.Light";
                public const string Sakura = "Settings.Theme.Options.Sakura";
                public const string Mint = "Settings.Theme.Options.Mint";
                public const string Lavender = "Settings.Theme.Options.Lavender";
                public const string Ocean = "Settings.Theme.Options.Ocean";
                public const string Sunset = "Settings.Theme.Options.Sunset";
                public const string Forest = "Settings.Theme.Options.Forest";
                public const string Mocha = "Settings.Theme.Options.Mocha";
                public const string Slate = "Settings.Theme.Options.Slate";
            }
        }
        public const string Display = "Settings.Display";
        public static class RemoveBrackets
        {
            public const string Title = "Settings.RemoveBrackets.Title";
            public const string Description = "Settings.RemoveBrackets.Description";
        }
        public static class IconSize
        {
            public const string Title = "Settings.IconSize.Title";
            public const string Description = "Settings.IconSize.Description";
        }
        public static class EnableHoverIcon
        {
            public const string Title = "Settings.EnableHoverIcon.Title";
            public const string Description = "Settings.EnableHoverIcon.Description";
        }
        public static class HoverIconSize
        {
            public const string Title = "Settings.HoverIconSize.Title";
            public const string Description = "Settings.HoverIconSize.Description";
        }
        public static class AntiAliasing
        {
            public const string Title = "Settings.AntiAliasing.Title";
            public const string Description = "Settings.AntiAliasing.Description";
            public static class Options
            {
                public const string None = "Settings.AntiAliasing.Options.None";
                public const string Low = "Settings.AntiAliasing.Options.Low";
                public const string Medium = "Settings.AntiAliasing.Options.Medium";
                public const string High = "Settings.AntiAliasing.Options.High";
            }
        }
        public static class ItemsPerPage
        {
            public const string Title = "Settings.ItemsPerPage.Title";
            public const string Description = "Settings.ItemsPerPage.Description";
        }
        public static class ThumbnailCompressionMaxSize
        {
            public const string Title = "Settings.ThumbnailCompressionMaxSize.Title";
            public const string Description = "Settings.ThumbnailCompressionMaxSize.Description";
        }
        public const string Item = "Settings.Item";
        public static class RemoveOriginal
        {
            public const string Title = "Settings.RemoveOriginal.Title";
            public const string Description = "Settings.RemoveOriginal.Description";
        }
        public static class LinkToOriginal
        {
            public const string Title = "Settings.LinkToOriginal.Title";
            public const string Description = "Settings.LinkToOriginal.Description";
        }
        public static class TreatEmptySupportedAvatarAsNone
        {
            public const string Title = "Settings.TreatEmptySupportedAvatarAsNone.Title";
            public const string Description = "Settings.TreatEmptySupportedAvatarAsNone.Description";
        }
        public const string Background = "Settings.Background";
        public static class UseCustomBackground
        {
            public const string Title = "Settings.UseCustomBackground.Title";
            public const string Description = "Settings.UseCustomBackground.Description";
        }
        public static class BackgroundImage
        {
            public const string Title = "Settings.BackgroundImage.Title";
            public const string Description = "Settings.BackgroundImage.Description";
            public const string Browse = "Settings.BackgroundImage.Browse";
        }
        public static class Opacity
        {
            public const string Title = "Settings.Opacity.Title";
            public const string Description = "Settings.Opacity.Description";
        }
        public const string CommonAvatar = "Settings.CommonAvatar";
        public static class CommonAvatarManagement
        {
            public const string Title = "Settings.CommonAvatarManagement.Title";
            public const string Description = "Settings.CommonAvatarManagement.Description";
            public const string OpenManagement = "Settings.CommonAvatarManagement.OpenManagement";
        }
        public const string DataManagement = "Settings.DataManagement";
        public static class ItemsFolder
        {
            public const string Title = "Settings.ItemsFolder.Title";
            public const string Description = "Settings.ItemsFolder.Description";
            public const string Browse = "Settings.ItemsFolder.Browse";
        }
        public static class AutoBackupPath
        {
            public const string Title = "Settings.AutoBackupPath.Title";
            public const string Description = "Settings.AutoBackupPath.Description";
            public const string Browse = "Settings.AutoBackupPath.Browse";
        }
        public static class AutoBackupInterval
        {
            public const string Title = "Settings.AutoBackupInterval.Title";
            public const string Description = "Settings.AutoBackupInterval.Description";
        }
        public static class ImportFromOther
        {
            public const string Title = "Settings.ImportFromOther.Title";
            public const string Description = "Settings.ImportFromOther.Description";
            public const string Import = "Settings.ImportFromOther.Import";
        }
        public static class FetchAllThumbnails
        {
            public const string Title = "Settings.FetchAllThumbnails.Title";
            public const string Description = "Settings.FetchAllThumbnails.Description";
            public const string Open = "Settings.FetchAllThumbnails.Open";
        }
        public static class FetchAllVariationHashs
        {
            public const string Title = "Settings.FetchAllVariationHashs.Title";
            public const string Description = "Settings.FetchAllVariationHashs.Description";
            public const string Open = "Settings.FetchAllVariationHashs.Open";
        }
        public static class RestoreFromBackup
        {
            public const string Title = "Settings.RestoreFromBackup.Title";
            public const string Description = "Settings.RestoreFromBackup.Description";
            public const string SelectBackup = "Settings.RestoreFromBackup.SelectBackup";
        }
        public static class AutoFixDatabase
        {
            public const string Title = "Settings.AutoFixDatabase.Title";
            public const string Description = "Settings.AutoFixDatabase.Description";
            public const string Fix = "Settings.AutoFixDatabase.Fix";
        }
        public static class ResetDatabase
        {
            public const string Title = "Settings.ResetDatabase.Title";
            public const string Description = "Settings.ResetDatabase.Description";
            public const string Open = "Settings.ResetDatabase.Open";
        }
        public const string System = "Settings.System";
        public static class ErrorLog
        {
            public const string Title = "Settings.ErrorLog.Title";
            public const string Description = "Settings.ErrorLog.Description";
            public const string OpenErrorLog = "Settings.ErrorLog.OpenErrorLog";
        }
        public static class RegisterScheme
        {
            public static class VRCAE
            {
                public const string Title = "Settings.RegisterScheme.VRCAE.Title";
                public const string Description = "Settings.RegisterScheme.VRCAE.Description";
            }
            public static class BLM
            {
                public const string Title = "Settings.RegisterScheme.BLM.Title";
                public const string Description = "Settings.RegisterScheme.BLM.Description";
            }
            public const string Register = "Settings.RegisterScheme.Register";
            public const string Unregister = "Settings.RegisterScheme.Unregister";
            public static class Status
            {
                public const string Own = "Settings.RegisterScheme.Status.Own";
                public const string Other = "Settings.RegisterScheme.Status.Other";
                public const string None = "Settings.RegisterScheme.Status.None";
            }
            public const string OverwriteConfirm = "Settings.RegisterScheme.OverwriteConfirm";
            public const string UnregisterConfirm = "Settings.RegisterScheme.UnregisterConfirm";
            public const string UnregisterSuccess = "Settings.RegisterScheme.UnregisterSuccess";
        }
        public static class MaxDegreeOfParallelism
        {
            public const string Title = "Settings.MaxDegreeOfParallelism.Title";
            public const string Description = "Settings.MaxDegreeOfParallelism.Description";
        }
        public static class CheckForUpdate
        {
            public const string Title = "Settings.CheckForUpdate.Title";
            public const string Description = "Settings.CheckForUpdate.Description";
        }
        public static class UpdateChannel
        {
            public const string Title = "Settings.UpdateChannel.Title";
            public const string Description = "Settings.UpdateChannel.Description";
            public static class Options
            {
                public const string Stable = "Settings.UpdateChannel.Options.Stable";
                public const string Beta = "Settings.UpdateChannel.Options.Beta";
            }
        }
        public static class CheckForUpdateNow
        {
            public const string Title = "Settings.CheckForUpdateNow.Title";
            public const string Description = "Settings.CheckForUpdateNow.Description";
            public const string Check = "Settings.CheckForUpdateNow.Check";
        }
        public const string Apply = "Settings.Apply";
        public const string About = "Settings.About";
        public static class AboutInfo
        {
            public const string Title = "Settings.AboutInfo.Title";
            public const string Subtitle = "Settings.AboutInfo.Subtitle";
        }
        public static class AboutDeveloper
        {
            public const string Title = "Settings.AboutDeveloper.Title";
            public const string Label = "Settings.AboutDeveloper.Label";
        }
        public static class AboutProject
        {
            public const string Title = "Settings.AboutProject.Title";
            public const string SourceCodeDescription = "Settings.AboutProject.SourceCodeDescription";
            public const string ViewRepository = "Settings.AboutProject.ViewRepository";
        }
        public static class AboutLicense
        {
            public const string Title = "Settings.AboutLicense.Title";
            public const string Type = "Settings.AboutLicense.Type";
            public const string Description = "Settings.AboutLicense.Description";
            public const string ViewLicense = "Settings.AboutLicense.ViewLicense";
            public const string ViewThirdParty = "Settings.AboutLicense.ViewThirdParty";
        }
    }
    public static class SidePanel
    {
        public const string AdvancedSearch = "SidePanel.AdvancedSearch";
        public const string BulkImport = "SidePanel.BulkImport";
        public const string BulkImportPreset = "SidePanel.BulkImportPreset";
    }
    public static class AdvancedSearch
    {
        public const string OrSearch = "AdvancedSearch.OrSearch";
        public const string NegationHint = "AdvancedSearch.NegationHint";
        public const string Title = "AdvancedSearch.Title";
        public const string Author = "AdvancedSearch.Author";
        public const string BoothId = "AdvancedSearch.BoothId";
        public const string SupportedAvatar = "AdvancedSearch.SupportedAvatar";
        public const string Category = "AdvancedSearch.Category";
        public const string Memo = "AdvancedSearch.Memo";
        public const string ImplementedAvatar = "AdvancedSearch.ImplementedAvatar";
        public const string NotImplementedAvatar = "AdvancedSearch.NotImplementedAvatar";
        public const string Tag = "AdvancedSearch.Tag";
        public const string CommonAvatar = "AdvancedSearch.CommonAvatar";
    }
    public static class BulkImport
    {
        public const string Import = "BulkImport.Import";
        public const string Save = "BulkImport.Save";
        public const string Reset = "BulkImport.Reset";
    }
    public static class ItemEditor
    {
        public const string BoothItemInfo = "ItemEditor.BoothItemInfo";
        public const string AddFolder = "ItemEditor.AddFolder";
        public const string AddFile = "ItemEditor.AddFile";
        public const string AddUrl = "ItemEditor.AddUrl";
        public const string BoothUrl = "ItemEditor.BoothUrl";
        public const string BoothUrlPlaceholder = "ItemEditor.BoothUrlPlaceholder";
        public const string FetchInfo = "ItemEditor.FetchInfo";
        public const string Title = "ItemEditor.Title";
        public const string Author = "ItemEditor.Author";
        public const string Category = "ItemEditor.Category";
        public const string SupportedAvatars = "ItemEditor.SupportedAvatars";
        public const string SelectedAvatarsCount = "ItemEditor.SelectedAvatarsCount";
        public const string ShowAdvancedSettings = "ItemEditor.ShowAdvancedSettings";
        public const string ItemMemo = "ItemEditor.ItemMemo";
        public const string EditItemMemo = "ItemEditor.EditItemMemo";
        public const string Tags = "ItemEditor.Tags";
        public const string SelectedTagsCount = "ItemEditor.SelectedTagsCount";
        public const string ShowInternalInfo = "ItemEditor.ShowInternalInfo";
        public const string AuthorId = "ItemEditor.AuthorId";
        public const string BoothId = "ItemEditor.BoothId";
        public const string ImageUrl = "ItemEditor.ImageUrl";
        public const string DownloadURL = "ItemEditor.DownloadURL";
        public const string ConfirmAndSave = "ItemEditor.ConfirmAndSave";
        public static class LinkToOriginal
        {
            public const string Title = "ItemEditor.LinkToOriginal.Title";
            public const string Description = "ItemEditor.LinkToOriginal.Description";
        }
        public const string RemoveFolder = "ItemEditor.RemoveFolder";
    }
    public static class SelectAvatars
    {
        public static class Title
        {
            public const string SupportedAvatars = "SelectAvatars.Title.SupportedAvatars";
            public const string ImplementedAvatars = "SelectAvatars.Title.ImplementedAvatars";
        }
        public const string Search = "SelectAvatars.Search";
        public const string AddTempAvatar = "SelectAvatars.AddTempAvatar";
    }
    public static class EditCommonAvatars
    {
        public const string Title = "EditCommonAvatars.Title";
        public const string Group = "EditCommonAvatars.Group";
        public const string AddGroup = "EditCommonAvatars.AddGroup";
        public const string RenameGroup = "EditCommonAvatars.RenameGroup";
        public const string RemoveGroup = "EditCommonAvatars.RemoveGroup";
        public const string Search = "EditCommonAvatars.Search";
        public const string ReplaceToGroup = "EditCommonAvatars.ReplaceToGroup";
    }
    public static class ResolveTempAvatar
    {
        public const string Title = "ResolveTempAvatar.Title";
        public const string Search = "ResolveTempAvatar.Search";
    }
    public static class ErrorLog
    {
        public const string Title = "ErrorLog.Title";
        public const string OpenLogFolder = "ErrorLog.OpenLogFolder";
    }
    public static class InitialSetup
    {
        public const string ChangeLaterNotice = "InitialSetup.ChangeLaterNotice";
    }
    public static class EditMemo
    {
        public const string Title = "EditMemo.Title";
        public const string Memo = "EditMemo.Memo";
    }
    public static class EditTags
    {
        public const string Title = "EditTags.Title";
        public const string AddTag = "EditTags.AddTag";
        public const string NewTag = "EditTags.NewTag";
        public const string SelectTag = "EditTags.SelectTag";
    }
    public static class ImportData
    {
        public const string Title = "ImportData.Title";
        public const string Description = "ImportData.Description";
        public const string ImportSource = "ImportData.ImportSource";
        public static class FolderPath
        {
            public const string Title = "ImportData.FolderPath.Title";
            public const string Browse = "ImportData.FolderPath.Browse";
        }
        public const string Import = "ImportData.Import";
        public const string SelectData = "ImportData.SelectData";
        public const string Database = "ImportData.Database";
        public const string Thumbnails = "ImportData.Thumbnails";
    }
    public static class ExportData
    {
        public const string Title = "ExportData.Title";
        public const string Description = "ExportData.Description";
        public const string ExportType = "ExportData.ExportType";
        public static class FolderPath
        {
            public const string Title = "ExportData.FolderPath.Title";
            public const string Browse = "ExportData.FolderPath.Browse";
        }
        public const string IncludeCommonToSupported = "ExportData.IncludeCommonToSupported";
        public const string Export = "ExportData.Export";
    }
    public static class ResetDatabase
    {
        public const string Title = "ResetDatabase.Title";
        public const string Description = "ResetDatabase.Description";
        public const string SelectDatabases = "ResetDatabase.SelectDatabases";
        public const string ItemDatabase = "ResetDatabase.ItemDatabase";
        public const string TempAvatarDatabase = "ResetDatabase.TempAvatarDatabase";
        public const string CommonAvatarDatabase = "ResetDatabase.CommonAvatarDatabase";
        public const string BulkImportPresetDatabase = "ResetDatabase.BulkImportPresetDatabase";
        public const string Reset = "ResetDatabase.Reset";
    }
    public static class FetchAllThumbnails
    {
        public const string Title = "FetchAllThumbnails.Title";
        public const string Description = "FetchAllThumbnails.Description";
        public const string Start = "FetchAllThumbnails.Start";
        public const string CancelRunning = "FetchAllThumbnails.CancelRunning";
        public const string CurrentItem = "FetchAllThumbnails.CurrentItem";
        public const string Progress = "FetchAllThumbnails.Progress";
        public const string Eta = "FetchAllThumbnails.Eta";
        public const string EtaUnknown = "FetchAllThumbnails.EtaUnknown";
        public static class Status
        {
            public const string Ready = "FetchAllThumbnails.Status.Ready";
            public const string Running = "FetchAllThumbnails.Status.Running";
            public const string Cancelling = "FetchAllThumbnails.Status.Cancelling";
            public const string Cancelled = "FetchAllThumbnails.Status.Cancelled";
            public const string Completed = "FetchAllThumbnails.Status.Completed";
        }
    }
    public static class FetchAllVariationHashs
    {
        public const string Title = "FetchAllVariationHashs.Title";
        public const string Description = "FetchAllVariationHashs.Description";
        public const string Start = "FetchAllVariationHashs.Start";
        public const string CancelRunning = "FetchAllVariationHashs.CancelRunning";
        public const string CurrentItem = "FetchAllVariationHashs.CurrentItem";
        public const string Progress = "FetchAllVariationHashs.Progress";
        public const string Eta = "FetchAllVariationHashs.Eta";
        public const string EtaUnknown = "FetchAllVariationHashs.EtaUnknown";
        public static class Status
        {
            public const string Ready = "FetchAllVariationHashs.Status.Ready";
            public const string Running = "FetchAllVariationHashs.Status.Running";
            public const string Cancelling = "FetchAllVariationHashs.Status.Cancelling";
            public const string Cancelled = "FetchAllVariationHashs.Status.Cancelled";
            public const string Completed = "FetchAllVariationHashs.Status.Completed";
        }
    }
    public static class UpdateDialog
    {
        public const string Available = "UpdateDialog.Available";
        public const string VersionText = "UpdateDialog.VersionText";
        public const string ChangeLogs = "UpdateDialog.ChangeLogs";
        public const string Later = "UpdateDialog.Later";
        public const string UpdateNow = "UpdateDialog.UpdateNow";
        public const string NoUpdateAvailableTitle = "UpdateDialog.NoUpdateAvailableTitle";
        public const string NoUpdateAvailable = "UpdateDialog.NoUpdateAvailable";
    }
    public static class ArchivePasswordDialog
    {
        public const string Title = "ArchivePasswordDialog.Title";
        public const string Description = "ArchivePasswordDialog.Description";
        public const string FileName = "ArchivePasswordDialog.FileName";
        public const string Attempts = "ArchivePasswordDialog.Attempts";
        public const string Placeholder = "ArchivePasswordDialog.Placeholder";
    }
    public static class MergeCategory
    {
        public const string Title = "MergeCategory.Title";
        public const string SourceCategory = "MergeCategory.SourceCategory";
        public const string TargetCategory = "MergeCategory.TargetCategory";
        public const string Merge = "MergeCategory.Merge";
    }
    public static class UnitypackageViewer
    {
        public const string Export = "UnitypackageViewer.Export";
        public const string Title = "UnitypackageViewer.Title";
        public static class Status
        {
            public const string Loading = "UnitypackageViewer.Status.Loading";
            public const string LoadFailed = "UnitypackageViewer.Status.LoadFailed";
            public const string Entries = "UnitypackageViewer.Status.Entries";
        }
    }
    public static class DialogResult
    {
        public const string OK = "DialogResult.OK";
        public const string Yes = "DialogResult.Yes";
        public const string No = "DialogResult.No";
    }
}
