/// ****************************************************************************************************
///
/// <auto-generated>
///     This file was generated during the build process from UI locale data (locales/ja-JP.json).
///     DO NOT EDIT THIS FILE MANUALLY.
///
///     To regenerate, run `dotnet run` in the LocalizationKeyGenerator project
///     or build the AvatarExplorer.Core project.
/// </auto-generated>
///
/// ****************************************************************************************************

namespace AvatarExplorer.Core.Localization;

public static class LocalizationKey
{
    public const string LanguageName = "LanguageName";
    public const string LanguagePriority = "LanguagePriority";
    public const string BoothLanguageCode = "BoothLanguageCode";
    public static class Title
    {
        public const string AdministratorMode = "Title.AdministratorMode";
    }
    public static class Main
    {
        public static class Search
        {
            public const string Watermark = "Main.Search.Watermark";
        }
        public const string AddItem = "Main.AddItem";
        public static class Filter
        {
            public const string Avatar = "Main.Filter.Avatar";
            public const string Author = "Main.Filter.Author";
            public const string Category = "Main.Filter.Category";
        }
        public static class Path
        {
            public const string Watermark = "Main.Path.Watermark";
            public const string SearchResult = "Main.Path.SearchResult";
            public static class Root
            {
                public const string Avatar = "Main.Path.Root.Avatar";
                public const string Author = "Main.Path.Root.Author";
                public const string Category = "Main.Path.Root.Category";
            }
            public const string Search = "Main.Path.Search";
            public const string Removed = "Main.Path.Removed";
        }
    }
    public static class ItemCategory
    {
        public const string Avatar = "ItemCategory.Avatar";
        public const string Clothing = "ItemCategory.Clothing";
        public const string Texture = "ItemCategory.Texture";
        public const string Gimmick = "ItemCategory.Gimmick";
        public const string Accessory = "ItemCategory.Accessory";
        public const string HairStyle = "ItemCategory.HairStyle";
        public const string Animation = "ItemCategory.Animation";
        public const string Tool = "ItemCategory.Tool";
        public const string Shader = "ItemCategory.Shader";
    }
    public static class Button
    {
        public static class Description
        {
            public static class Item
            {
                public const string Author = "Button.Description.Item.Author";
                public const string Count = "Button.Description.Item.Count";
            }
            public static class File
            {
                public const string Extension = "Button.Description.File.Extension";
            }
            public static class CommonAvatar
            {
                public const string Count = "Button.Description.CommonAvatar.Count";
            }
            public static class BulkImportPreset
            {
                public const string Count = "Button.Description.BulkImportPreset.Count";
            }
            public const string TempAvatar = "Button.Description.TempAvatar";
        }
        public static class Tag
        {
            public const string CommonAvatar = "Button.Tag.CommonAvatar";
        }
        public static class ToolTip
        {
            public const string CreatedDate = "Button.ToolTip.CreatedDate";
            public const string UpdatedDate = "Button.ToolTip.UpdatedDate";
            public const string FilePath = "Button.ToolTip.FilePath";
        }
        public const string Close = "Button.Close";
        public const string Confirm = "Button.Confirm";
        public const string Cancel = "Button.Cancel";
    }
    public static class ItemWindow
    {
        public const string CurrentPage = "ItemWindow.CurrentPage";
        public const string PageItemCount = "ItemWindow.PageItemCount";
    }
    public static class Dialog
    {
        public static class Confirmation
        {
            public const string Default = "Dialog.Confirmation.Default";
            public const string RemoveItem = "Dialog.Confirmation.RemoveItem";
            public const string ResetItemDatabase = "Dialog.Confirmation.ResetItemDatabase";
            public const string ResetCommonAvatarDatabase = "Dialog.Confirmation.ResetCommonAvatarDatabase";
            public const string ResetBulkImportPresetDatabase = "Dialog.Confirmation.ResetBulkImportPresetDatabase";
            public const string RemoveCommonAvatarGroup = "Dialog.Confirmation.RemoveCommonAvatarGroup";
            public const string RemoveTempAvatar = "Dialog.Confirmation.RemoveTempAvatar";
            public const string ContinueRestoreFromBackup = "Dialog.Confirmation.ContinueRestoreFromBackup";
            public const string RemovePreset = "Dialog.Confirmation.RemovePreset";
            public const string AddToExistingItem = "Dialog.Confirmation.AddToExistingItem";
            public const string ResolveTempAvatar = "Dialog.Confirmation.ResolveTempAvatar";
            public const string RemoveAssetData = "Dialog.Confirmation.RemoveAssetData";
            public static class ExportToCsv
            {
                public const string IncludeImplementedToSupported = "Dialog.Confirmation.ExportToCsv.IncludeImplementedToSupported";
            }
            public static class EditCommonAvatars
            {
                public const string ReplaceAvatarsToGroup = "Dialog.Confirmation.EditCommonAvatars.ReplaceAvatarsToGroup";
                public const string ReplaceGroupToAvatars = "Dialog.Confirmation.EditCommonAvatars.ReplaceGroupToAvatars";
            }
            public static class StoragePathChange
            {
                public const string CopyData = "Dialog.Confirmation.StoragePathChange.CopyData";
            }
            public const string DuplicateCustomCategoryName = "Dialog.Confirmation.DuplicateCustomCategoryName";
        }
        public static class Title
        {
            public const string NewItemTitle = "Dialog.Title.NewItemTitle";
            public const string AddCustomCategory = "Dialog.Title.AddCustomCategory";
            public const string AddCommonAvatarGroup = "Dialog.Title.AddCommonAvatarGroup";
            public const string NewCommonAvatarGroupName = "Dialog.Title.NewCommonAvatarGroupName";
            public const string NewBulkImportPresetName = "Dialog.Title.NewBulkImportPresetName";
            public const string NewTempAvatarName = "Dialog.Title.NewTempAvatarName";
            public const string NewCustomCategoryName = "Dialog.Title.NewCustomCategoryName";
        }
        public const string SelectSaveFilePath = "Dialog.SelectSaveFilePath";
        public const string SelectFolderPath = "Dialog.SelectFolderPath";
        public const string SelectFilePath = "Dialog.SelectFilePath";
    }
    public static class AddItem
    {
        public const string SelectedAvatarsCount = "AddItem.SelectedAvatarsCount";
        public const string RemoveFolder = "AddItem.RemoveFolder";
        public const string BoothItemInfo = "AddItem.BoothItemInfo";
        public const string AddFolder = "AddItem.AddFolder";
        public const string AddFile = "AddItem.AddFile";
        public const string BoothUrl = "AddItem.BoothUrl";
        public const string BoothUrlWatermark = "AddItem.BoothUrlWatermark";
        public const string FetchInfo = "AddItem.FetchInfo";
        public const string Title = "AddItem.Title";
        public const string Author = "AddItem.Author";
        public const string Category = "AddItem.Category";
        public const string SupportedAvatars = "AddItem.SupportedAvatars";
        public const string ShowInternalInfo = "AddItem.ShowInternalInfo";
        public const string AuthorId = "AddItem.AuthorId";
        public const string BoothId = "AddItem.BoothId";
        public const string ImageUrl = "AddItem.ImageUrl";
        public const string AuthorImageUrl = "AddItem.AuthorImageUrl";
        public const string ConfirmAndSave = "AddItem.ConfirmAndSave";
    }
    public static class Scheme
    {
        public const string PathChanged = "Scheme.PathChanged";
        public const string RegisterAgain = "Scheme.RegisterAgain";
        public const string Register = "Scheme.Register";
        public const string RestartAsAdmin = "Scheme.RestartAsAdmin";
        public const string RegisterSuccess = "Scheme.RegisterSuccess";
        public const string RegisterSkipped = "Scheme.RegisterSkipped";
    }
    public static class FileCategory
    {
        public const string Modification = "FileCategory.Modification";
        public const string Texture = "FileCategory.Texture";
        public const string Document = "FileCategory.Document";
        public const string Unitypackage = "FileCategory.Unitypackage";
        public const string Material = "FileCategory.Material";
        public const string UrlShortcut = "FileCategory.UrlShortcut";
        public const string Font = "FileCategory.Font";
        public const string Unknown = "FileCategory.Unknown";
    }
    public static class Processing
    {
        public static class Unitypackage
        {
            public static class Status
            {
                public const string Preparing = "Processing.Unitypackage.Status.Preparing";
                public const string Extracting = "Processing.Unitypackage.Status.Extracting";
                public const string Creating = "Processing.Unitypackage.Status.Creating";
                public const string Completed = "Processing.Unitypackage.Status.Completed";
            }
        }
        public static class Booth
        {
            public static class Status
            {
                public const string Fetching = "Processing.Booth.Status.Fetching";
            }
        }
        public static class DirectoryCopy
        {
            public const string Copying = "Processing.DirectoryCopy.Copying";
        }
        public static class Import
        {
            public const string Copying = "Processing.Import.Copying";
        }
        public static class ItemAdd
        {
            public const string Copying = "Processing.ItemAdd.Copying";
        }
    }
    public static class ContextMenu
    {
        public static class Item
        {
            public const string OpenFolder = "ContextMenu.Item.OpenFolder";
            public const string ShowOtherItemsByAuthor = "ContextMenu.Item.ShowOtherItemsByAuthor";
            public static class Add
            {
                public const string BulkImportList = "ContextMenu.Item.Add.BulkImportList";
                public const string File = "ContextMenu.Item.Add.File";
                public const string Folder = "ContextMenu.Item.Add.Folder";
            }
            public static class Booth
            {
                public const string Open = "ContextMenu.Item.Booth.Open";
                public const string Copy = "ContextMenu.Item.Booth.Copy";
            }
            public static class Edit
            {
                public const string Default = "ContextMenu.Item.Edit.Default";
                public const string Title = "ContextMenu.Item.Edit.Title";
                public const string Tag = "ContextMenu.Item.Edit.Tag";
                public const string Memo = "ContextMenu.Item.Edit.Memo";
                public const string Implemented = "ContextMenu.Item.Edit.Implemented";
            }
            public static class Thumbnail
            {
                public const string Change = "ContextMenu.Item.Thumbnail.Change";
                public const string Fetch = "ContextMenu.Item.Thumbnail.Fetch";
            }
            public const string Remove = "ContextMenu.Item.Remove";
        }
        public static class ItemFile
        {
            public const string OpenFile = "ContextMenu.ItemFile.OpenFile";
            public const string BulkImportList = "ContextMenu.ItemFile.BulkImportList";
            public const string OpenFileInExplorer = "ContextMenu.ItemFile.OpenFileInExplorer";
        }
        public static class BulkImportPreset
        {
            public const string RemovePreset = "ContextMenu.BulkImportPreset.RemovePreset";
        }
        public static class TempAvatar
        {
            public const string EditTempAvatarName = "ContextMenu.TempAvatar.EditTempAvatarName";
            public const string ResolveTempAvatar = "ContextMenu.TempAvatar.ResolveTempAvatar";
            public const string RemoveTempAvatar = "ContextMenu.TempAvatar.RemoveTempAvatar";
        }
        public static class ItemCategory
        {
            public const string EditCustomCategoryName = "ContextMenu.ItemCategory.EditCustomCategoryName";
        }
    }
    public static class SearchFilter
    {
        public const string Default = "SearchFilter.Default";
        public const string Title = "SearchFilter.Title";
        public const string Author = "SearchFilter.Author";
        public const string Booth = "SearchFilter.Booth";
        public const string SupportedAvatar = "SearchFilter.SupportedAvatar";
        public const string Category = "SearchFilter.Category";
        public const string ItemMemo = "SearchFilter.ItemMemo";
        public const string FolderName = "SearchFilter.FolderName";
        public const string FileName = "SearchFilter.FileName";
        public const string ImplementedAvatar = "SearchFilter.ImplementedAvatar";
        public const string NotImplementedAvatar = "SearchFilter.NotImplementedAvatar";
        public const string Tag = "SearchFilter.Tag";
        public const string CommonAvatar = "SearchFilter.CommonAvatar";
        public const string SearchWord = "SearchFilter.SearchWord";
        public const string IsOrSearch = "SearchFilter.IsOrSearch";
    }
    public static class Success
    {
        public const string Default = "Success.Default";
        public const string Import = "Success.Import";
        public const string Export = "Success.Export";
        public const string ItemAdd = "Success.ItemAdd";
        public const string ItemEdit = "Success.ItemEdit";
        public const string ItemThumbnailEdit = "Success.ItemThumbnailEdit";
        public const string AuthorThumbnailEdit = "Success.AuthorThumbnailEdit";
        public const string Remove = "Success.Remove";
        public const string FetchItemThumbnail = "Success.FetchItemThumbnail";
        public const string ItemFileAdd = "Success.ItemFileAdd";
        public const string ItemFolderAdd = "Success.ItemFolderAdd";
        public const string CopyDirectory = "Success.CopyDirectory";
    }
    public static class Warning
    {
        public const string Default = "Warning.Default";
        public const string RunningInAdministratorMode = "Warning.RunningInAdministratorMode";
    }
    public static class Error
    {
        public const string Default = "Error.Default";
        public const string NotImplemented = "Error.NotImplemented";
        public const string Nothing = "Error.Nothing";
        public const string BoothItemNotFound = "Error.BoothItemNotFound";
        public const string BoothApiCooldown = "Error.BoothApiCooldown";
        public const string ItemNotFound = "Error.ItemNotFound";
        public const string CommonAvatarNotFound = "Error.CommonAvatarNotFound";
        public const string PresetNotFound = "Error.PresetNotFound";
        public static class Validation
        {
            public const string NoFolders = "Error.Validation.NoFolders";
            public const string EmptyTitle = "Error.Validation.EmptyTitle";
            public const string EmptyAuthor = "Error.Validation.EmptyAuthor";
        }
        public const string ImportFailed = "Error.ImportFailed";
        public const string ExportFailed = "Error.ExportFailed";
        public const string ItemAddFailed = "Error.ItemAddFailed";
        public const string ItemEditFailed = "Error.ItemEditFailed";
        public const string ItemThumbnailEditFailed = "Error.ItemThumbnailEditFailed";
        public const string AuthorThumbnailEditFailed = "Error.AuthorThumbnailEditFailed";
        public const string CopyDirectoryFailed = "Error.CopyDirectoryFailed";
        public const string OpenDialogFailed = "Error.OpenDialogFailed";
        public const string CheckSchemeFailed = "Error.CheckSchemeFailed";
        public const string BulkImportFailed = "Error.BulkImportFailed";
        public const string OpenFileFailed = "Error.OpenFileFailed";
        public const string OpenFolderFailed = "Error.OpenFolderFailed";
        public const string OpenUriFailed = "Error.OpenUriFailed";
        public const string ImportUnitypackageFailed = "Error.ImportUnitypackageFailed";
        public const string RegisterSchemeFailed = "Error.RegisterSchemeFailed";
        public const string RetrieveBoothItemFailed = "Error.RetrieveBoothItemFailed";
        public const string FetchItemThumbnailFailed = "Error.FetchItemThumbnailFailed";
        public const string ClipboardFailed = "Error.ClipboardFailed";
        public const string FoundProcessingFailedPath = "Error.FoundProcessingFailedPath";
        public const string AddItemFileFailed = "Error.AddItemFileFailed";
        public const string AddItemFolderFailed = "Error.AddItemFolderFailed";
        public const string RemoveFailed = "Error.RemoveFailed";
        public const string TempAvatarNotFound = "Error.TempAvatarNotFound";
        public const string LicenseFileNotFound = "Error.LicenseFileNotFound";
        public const string ThirdPartyLicenseFileNotFound = "Error.ThirdPartyLicenseFileNotFound";
    }
    public static class Settings
    {
        public const string Basic = "Settings.Basic";
        public static class Language
        {
            public const string Title = "Settings.Language.Title";
            public const string Description = "Settings.Language.Description";
        }
        public static class SortOrder
        {
            public const string Title = "Settings.SortOrder.Title";
            public const string Description = "Settings.SortOrder.Description";
            public static class Options
            {
                public const string Title = "Settings.SortOrder.Options.Title";
                public const string Author = "Settings.SortOrder.Options.Author";
                public const string Created = "Settings.SortOrder.Options.Created";
                public const string Updated = "Settings.SortOrder.Options.Updated";
            }
        }
        public static class Theme
        {
            public const string Title = "Settings.Theme.Title";
            public const string Description = "Settings.Theme.Description";
            public static class Options
            {
                public const string Dark = "Settings.Theme.Options.Dark";
                public const string Light = "Settings.Theme.Options.Light";
            }
        }
        public const string Display = "Settings.Display";
        public static class RemoveBrackets
        {
            public const string Title = "Settings.RemoveBrackets.Title";
            public const string Description = "Settings.RemoveBrackets.Description";
        }
        public static class IconSize
        {
            public const string Title = "Settings.IconSize.Title";
            public const string Description = "Settings.IconSize.Description";
        }
        public static class EnableHoverIcon
        {
            public const string Title = "Settings.EnableHoverIcon.Title";
            public const string Description = "Settings.EnableHoverIcon.Description";
        }
        public static class HoverIconSize
        {
            public const string Title = "Settings.HoverIconSize.Title";
            public const string Description = "Settings.HoverIconSize.Description";
        }
        public static class AntiAliasing
        {
            public const string Title = "Settings.AntiAliasing.Title";
            public const string Description = "Settings.AntiAliasing.Description";
            public static class Options
            {
                public const string None = "Settings.AntiAliasing.Options.None";
                public const string Low = "Settings.AntiAliasing.Options.Low";
                public const string Medium = "Settings.AntiAliasing.Options.Medium";
                public const string High = "Settings.AntiAliasing.Options.High";
            }
        }
        public static class ItemsPerPage
        {
            public const string Title = "Settings.ItemsPerPage.Title";
            public const string Description = "Settings.ItemsPerPage.Description";
        }
        public const string Item = "Settings.Item";
        public static class RemoveOriginal
        {
            public const string Title = "Settings.RemoveOriginal.Title";
            public const string Description = "Settings.RemoveOriginal.Description";
        }
        public const string Background = "Settings.Background";
        public static class UseCustomBackground
        {
            public const string Title = "Settings.UseCustomBackground.Title";
            public const string Description = "Settings.UseCustomBackground.Description";
        }
        public static class BackgroundImage
        {
            public const string Title = "Settings.BackgroundImage.Title";
            public const string Description = "Settings.BackgroundImage.Description";
            public const string Browse = "Settings.BackgroundImage.Browse";
        }
        public static class Opacity
        {
            public const string Title = "Settings.Opacity.Title";
            public const string Description = "Settings.Opacity.Description";
        }
        public const string CommonAvatar = "Settings.CommonAvatar";
        public static class CommonAvatarManagement
        {
            public const string Title = "Settings.CommonAvatarManagement.Title";
            public const string Description = "Settings.CommonAvatarManagement.Description";
            public const string OpenManagement = "Settings.CommonAvatarManagement.OpenManagement";
        }
        public const string Data = "Settings.Data";
        public static class ItemsFolder
        {
            public const string Title = "Settings.ItemsFolder.Title";
            public const string Description = "Settings.ItemsFolder.Description";
            public const string Browse = "Settings.ItemsFolder.Browse";
        }
        public static class AutoBackupPath
        {
            public const string Title = "Settings.AutoBackupPath.Title";
            public const string Description = "Settings.AutoBackupPath.Description";
            public const string Browse = "Settings.AutoBackupPath.Browse";
        }
        public static class AutoBackupInterval
        {
            public const string Title = "Settings.AutoBackupInterval.Title";
            public const string Description = "Settings.AutoBackupInterval.Description";
        }
        public static class ImportFromOther
        {
            public const string Title = "Settings.ImportFromOther.Title";
            public const string Description = "Settings.ImportFromOther.Description";
            public const string Import = "Settings.ImportFromOther.Import";
        }
        public static class ExportCsv
        {
            public const string Title = "Settings.ExportCsv.Title";
            public const string Description = "Settings.ExportCsv.Description";
            public const string Export = "Settings.ExportCsv.Export";
        }
        public static class RestoreFromBackup
        {
            public const string Title = "Settings.RestoreFromBackup.Title";
            public const string Description = "Settings.RestoreFromBackup.Description";
            public const string SelectBackup = "Settings.RestoreFromBackup.SelectBackup";
        }
        public static class ResetItemDatabase
        {
            public const string Title = "Settings.ResetItemDatabase.Title";
            public const string Description = "Settings.ResetItemDatabase.Description";
            public const string Reset = "Settings.ResetItemDatabase.Reset";
        }
        public static class ResetCommonAvatarDatabase
        {
            public const string Title = "Settings.ResetCommonAvatarDatabase.Title";
            public const string Description = "Settings.ResetCommonAvatarDatabase.Description";
            public const string Reset = "Settings.ResetCommonAvatarDatabase.Reset";
        }
        public static class ResetBulkImportPresetDatabase
        {
            public const string Title = "Settings.ResetBulkImportPresetDatabase.Title";
            public const string Description = "Settings.ResetBulkImportPresetDatabase.Description";
            public const string Reset = "Settings.ResetBulkImportPresetDatabase.Reset";
        }
        public const string System = "Settings.System";
        public static class ErrorLog
        {
            public const string Title = "Settings.ErrorLog.Title";
            public const string Description = "Settings.ErrorLog.Description";
            public const string OpenErrorLog = "Settings.ErrorLog.OpenErrorLog";
        }
        public static class RegisterScheme
        {
            public const string Title = "Settings.RegisterScheme.Title";
            public const string Description = "Settings.RegisterScheme.Description";
            public const string Register = "Settings.RegisterScheme.Register";
        }
        public static class MaxDegreeOfParallelism
        {
            public const string Title = "Settings.MaxDegreeOfParallelism.Title";
            public const string Description = "Settings.MaxDegreeOfParallelism.Description";
        }
        public static class CheckForUpdate
        {
            public const string Title = "Settings.CheckForUpdate.Title";
            public const string Description = "Settings.CheckForUpdate.Description";
        }
        public static class UpdateChannel
        {
            public const string Title = "Settings.UpdateChannel.Title";
            public const string Description = "Settings.UpdateChannel.Description";
            public static class Options
            {
                public const string Stable = "Settings.UpdateChannel.Options.Stable";
                public const string Beta = "Settings.UpdateChannel.Options.Beta";
            }
        }
        public static class CheckForUpdateNow
        {
            public const string Title = "Settings.CheckForUpdateNow.Title";
            public const string Description = "Settings.CheckForUpdateNow.Description";
            public const string Check = "Settings.CheckForUpdateNow.Check";
        }
        public const string Apply = "Settings.Apply";
        public const string About = "Settings.About";
        public static class AboutInfo
        {
            public const string Title = "Settings.AboutInfo.Title";
            public const string Subtitle = "Settings.AboutInfo.Subtitle";
            public const string Version = "Settings.AboutInfo.Version";
        }
        public static class AboutDeveloper
        {
            public const string Title = "Settings.AboutDeveloper.Title";
            public const string Label = "Settings.AboutDeveloper.Label";
        }
        public static class AboutProject
        {
            public const string Title = "Settings.AboutProject.Title";
            public const string SourceCodeDescription = "Settings.AboutProject.SourceCodeDescription";
            public const string ViewRepository = "Settings.AboutProject.ViewRepository";
        }
        public static class AboutLicense
        {
            public const string Title = "Settings.AboutLicense.Title";
            public const string Type = "Settings.AboutLicense.Type";
            public const string Description = "Settings.AboutLicense.Description";
            public const string ViewLicense = "Settings.AboutLicense.ViewLicense";
            public const string ViewThirdParty = "Settings.AboutLicense.ViewThirdParty";
        }
    }
    public static class SidePanel
    {
        public const string AdvancedSearch = "SidePanel.AdvancedSearch";
        public const string BulkImport = "SidePanel.BulkImport";
        public const string BulkImportPreset = "SidePanel.BulkImportPreset";
    }
    public static class AdvancedSearch
    {
        public const string OrSearch = "AdvancedSearch.OrSearch";
        public const string Title = "AdvancedSearch.Title";
        public const string Author = "AdvancedSearch.Author";
        public const string BoothId = "AdvancedSearch.BoothId";
        public const string SupportedAvatar = "AdvancedSearch.SupportedAvatar";
        public const string Category = "AdvancedSearch.Category";
        public const string Memo = "AdvancedSearch.Memo";
        public const string Folder = "AdvancedSearch.Folder";
        public const string File = "AdvancedSearch.File";
        public const string ImplementedAvatar = "AdvancedSearch.ImplementedAvatar";
        public const string NotImplementedAvatar = "AdvancedSearch.NotImplementedAvatar";
        public const string Tag = "AdvancedSearch.Tag";
        public const string CommonAvatar = "AdvancedSearch.CommonAvatar";
    }
    public static class BulkImport
    {
        public const string Import = "BulkImport.Import";
        public const string Save = "BulkImport.Save";
        public const string Reset = "BulkImport.Reset";
    }
    public static class EditSupportedAvatars
    {
        public const string Title = "EditSupportedAvatars.Title";
        public const string Search = "EditSupportedAvatars.Search";
        public const string AddTempAvatar = "EditSupportedAvatars.AddTempAvatar";
    }
    public static class EditImplementedAvatars
    {
        public const string Title = "EditImplementedAvatars.Title";
    }
    public static class EditCommonAvatars
    {
        public const string Title = "EditCommonAvatars.Title";
        public const string Group = "EditCommonAvatars.Group";
        public const string AddGroup = "EditCommonAvatars.AddGroup";
        public const string RenameGroup = "EditCommonAvatars.RenameGroup";
        public const string RemoveGroup = "EditCommonAvatars.RemoveGroup";
        public const string ReplaceToGroup = "EditCommonAvatars.ReplaceToGroup";
    }
    public static class ResolveTempAvatar
    {
        public const string Title = "ResolveTempAvatar.Title";
        public const string Search = "ResolveTempAvatar.Search";
    }
    public static class ErrorLog
    {
        public const string Title = "ErrorLog.Title";
        public const string Reflesh = "ErrorLog.Reflesh";
    }
    public static class InitialSetup
    {
        public const string ChangeLaterNotice = "InitialSetup.ChangeLaterNotice";
    }
    public static class EditMemo
    {
        public const string Title = "EditMemo.Title";
        public const string Memo = "EditMemo.Memo";
    }
    public static class EditTags
    {
        public const string Title = "EditTags.Title";
        public const string AddTag = "EditTags.AddTag";
        public const string NewTag = "EditTags.NewTag";
        public const string SelectTag = "EditTags.SelectTag";
    }
    public static class SelectImportType
    {
        public const string Title = "SelectImportType.Title";
        public static class Options
        {
            public const string V1 = "SelectImportType.Options.V1";
            public const string KonoAsset = "SelectImportType.Options.KonoAsset";
        }
    }
    public static class Progress
    {
        public const string Loading = "Progress.Loading";
    }
    public static class UpdateDialog
    {
        public const string Available = "UpdateDialog.Available";
        public const string VersionText = "UpdateDialog.VersionText";
        public const string ChangeLogs = "UpdateDialog.ChangeLogs";
        public const string Later = "UpdateDialog.Later";
        public const string UpdateNow = "UpdateDialog.UpdateNow";
        public const string NoUpdateAvailableTitle = "UpdateDialog.NoUpdateAvailableTitle";
        public const string NoUpdateAvailable = "UpdateDialog.NoUpdateAvailable";
    }
    public static class DialogResult
    {
        public const string OK = "DialogResult.OK";
        public const string Yes = "DialogResult.Yes";
        public const string No = "DialogResult.No";
    }
}
