name: Flatpak Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
      
    runs-on: ${{ matrix.variant.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Dotnet Build
        run: dotnet publish "./AvatarExplorer.UI/AvatarExplorer.UI.csproj" -c Release -o ./.flatpak/publish -p:BuildTargetIsFlatpak=true -p:AvaloniaVersion=Nightly

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.github.puk06.vrc_avatar_explorer.flatpak
          manifest-path: .flatpak/com.github.puk06.vrc_avatar_explorer.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
