name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    needs: create-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
            extension: zip
          - os: windows-latest
            runtime: win-arm64
            extension: zip

          - os: macos-latest
            runtime: osx-arm64
            extension: zip
          - os: macos-13
            runtime: osx-x64
            extension: zip

          - os: ubuntu-latest
            runtime: linux-x64
            extension: tar.gz
          - os: ubuntu-latest
            runtime: linux-arm64
            extension: tar.gz
          - os: ubuntu-latest
            runtime: linux-musl-x64
            extension: tar.gz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Application
        run: |
          dotnet publish "./AvatarExplorer.UI/AvatarExplorer.UI.csproj" -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Compress
        shell: bash
        run: |
          APP_NAME="VRC-Avatar-Explorer"
          VERSION="${{ github.ref_name }}"
          RUNTIME="${{ matrix.runtime }}"
          EXTENSION="${{ matrix.extension }}"
          OUTPUT_NAME="${APP_NAME}_${VERSION#v}-${RUNTIME}.${EXTENSION}"
          cd publish
          if [ "$RUNNER_OS" == "Windows" ]; then
            powershell -Command "Compress-Archive -Path * -DestinationPath '../${OUTPUT_NAME}'"
          elif [ "${EXTENSION}" == "zip" ]; then
            zip -r "../${OUTPUT_NAME}" .
          else
            tar -czvf "../${OUTPUT_NAME}" .
          fi
          echo "ASSET_PATH=${OUTPUT_NAME}" >> $GITHUB_ENV

      - name: Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
