using System.Text;
using System.Text.Json;

string repositoryRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
string jsonPath = Path.Combine(repositoryRoot, "AvatarExplorer.Core", "Data", "Localization", "ja-JP.json");
string outputPath = Path.Combine(repositoryRoot, "AvatarExplorer.Core", "Localization", "LocalizationKeys.g.cs");

string json = File.ReadAllText(jsonPath);
Dictionary<string, string> dict = JsonSerializer.Deserialize<Dictionary<string, string>>(json)!;

Dictionary<string, object> tree = new();

foreach (var key in dict.Keys)
{
    string[] parts = key.Split('.');
    Dictionary<string, object> current = tree;

    for (int i = 0; i < parts.Length; i++)
    {
        string part = Sanitize(parts[i]);

        if (i == parts.Length - 1)
        {
            current[part] = key;
        }
        else
        {
            if (!current.ContainsKey(part))
            {
                current[part] = new Dictionary<string, object>();
            }

            current = (Dictionary<string, object>)current[part];
        }
    }
}

StringBuilder sb = new();

sb.AppendLine("/// ****************************************************************************************************");
sb.AppendLine("///");
sb.AppendLine("/// <auto-generated>");
sb.AppendLine("///     This file was generated during the build process from shared locale data (Data/Localization/ja-JP.json).");
sb.AppendLine("///     DO NOT EDIT THIS FILE MANUALLY.");
sb.AppendLine("///");
sb.AppendLine("///     To regenerate, run `dotnet run` in the LocalizationKeyGenerator project");
sb.AppendLine("///     or build the AvatarExplorer.Core project.");
sb.AppendLine("/// </auto-generated>");
sb.AppendLine("///");
sb.AppendLine("/// ****************************************************************************************************");
sb.AppendLine();
sb.AppendLine("namespace AvatarExplorer.Core.Localization;");
sb.AppendLine();
sb.AppendLine("public static class Loc");
sb.AppendLine("{");

WriteClass(tree, sb, 1);

sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString());

Console.WriteLine("Localization keys generated!");

static void WriteClass(Dictionary<string, object> dict, StringBuilder sb, int indent)
{
    string indentStr = new string(' ', indent * 4);

    foreach (var kvp in dict)
    {
        if (kvp.Value is string fullKey)
        {
            sb.AppendLine($"{indentStr}public const string {kvp.Key} = \"{fullKey}\";");
        }
        else if (kvp.Value is Dictionary<string, object> child)
        {
            sb.AppendLine($"{indentStr}public static class {kvp.Key}");
            sb.AppendLine($"{indentStr}{{");
            WriteClass(child, sb, indent + 1);
            sb.AppendLine($"{indentStr}}}");
        }
    }
}

static string Sanitize(string input)
{
    StringBuilder sb = new();
    if (!char.IsLetter(input[0])) sb.Append('_');

    foreach (char c in input)
    {
        sb.Append(char.IsLetterOrDigit(c) ? c : '_');
    }

    return sb.ToString();
}
